export const LIMITS = {
  MAX_MEMBERS_PER_GROUP: 10,
  MAX_GROUPS_PER_USER: 20,
  MAX_MESSAGE_LENGTH: 2000,
  MAX_GROUP_NAME_LENGTH: 50,
  INVITE_EXPIRY_DAYS: 7,
  MAX_IMAGE_SIZE_BYTES: 5 * 1024 * 1024, // 5MB
  MAX_IMAGES_PER_MESSAGE: 10,
  MAX_POLL_TITLE_LENGTH: 200,
  MAX_POLL_OPTION_LENGTH: 100,
  MIN_POLL_OPTIONS: 2,
  MAX_POLL_OPTIONS: 20,
  MAX_PAYMENT_TITLE_LENGTH: 200,
  MAX_PAYMENT_ITEM_DESCRIPTION_LENGTH: 200,
  MAX_PAYMENT_ITEMS: 20,
  MAX_PAYMENT_AMOUNT_CENTS: 10000000, // $100,000
  MIN_PAYMENT_AMOUNT_CENTS: 50, // $0.50 (Stripe minimum)
} as const;

export type Limits = typeof LIMITS;
